### PR TITLE
Sec QoL: add additional wanted statuses

### PR DESCRIPTION
**Pull request by FluffMe**
## About the PR
Adds the following wanted statuses to the game:
- Monitor
- Search

### To do before merge
- [x] Someone should work more on sprites. Current ones were hastily downscaled to 8x8.
    * [x] Add artist(s) to copyright. 
- [x] Admin discussion required on inclusion of "Kill on sight" status. Yes/**No**.
    * [x] ~~If yes, rule clarifications on its usage might be in order. Might be scoped to other PR.~~ Consensus is KoS is not required.
- [x] Testing needed for compatibility with criminal records events, like ninja hack. Just to make sure nothing breaks.

## Why / Balance
Should add a bit to gameplay and coordination of sec by making statuses more granular.
See [thread on discord](https://discord.com/channels/1139716325627932682/1302400582224445490).

### Upstream
- `Content.Shared/Security/SecurityStatus.cs` -- Security status enum.
    * added new statuses.
- `Content.Client/CriminalRecords/CriminalRecordsConsoleWindow.xaml.cs` -- UI for records console.
    * added new statuses to condition that prompts for reason popup.
- `Content.Server/CriminalRecords/Systems/CriminalRecordsConsoleSystem.cs` -- Records system.
    * added status change logic and chat notifications.
- `Content.Shared/CriminalRecords/Systems/SharedCriminalRecordsSystem.cs` -- Shared records system.
    * added status icon assignment.

- `Resources/Locale/en-US/cartridge-loader/cartridges.ftl` -- patch PDA app loc string for wanted status.

### Harmony
- `Resources/Locale/en-US/_Harmony/criminal-records/criminal-records.ftl` -- new loc strings.
- `Resources/Prototypes/_Harmony/StatusIcon/security.yml` -- status icon prototypes.
- `Resources/Textures/_Harmony/Interface/Misc/security_icons.rsi/*` -- new status icon textures

### Console UI
image

### Monitor status
image
image
image

### Search status
image
image
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- add: Added two new wanted statuses to the criminal records: monitor and search.

### CODE REVIEW

**Comment by DieselMohawk** [comment]
Tested Ninja interaction, works properly.

**Comment by DieselMohawk** [comment]
Am I supposed to review my own work? That's odd. Anyways, hope we get an admin concensus eventually.

**Comment by FluffMe** [comment]
> Am I supposed to review my own work? That's odd. Anyways, hope we get an admin concensus eventually.

Yes XD when it will be un-drafted you'll get the request.

**Comment by DieselMohawk** [comment]
I personally think KOS isn't needed since most Wanted killings are contextual.

**Comment by DieselMohawk** [comment]
I guess that's the checklist then. Since I made the sprites I'll leave the review to someone else, I guess?

**Comment by DieselMohawk** [comment]
I'm kinda lost right now

**Comment by FluffMe** [comment]
> I guess that's the checklist then. Since I made the sprites I'll leave the review to someone else, I guess?

Slap a review on, as you are only sprites owner. But it's for keld to approve in the end, yes.

**Comment by DieselMohawk** [comment]
> > I guess that's the checklist then. Since I made the sprites I'll leave the review to someone else, I guess?
> 
> Slap a review on, as you are only sprites owner. But it's for keld to approve in the end, yes.

Fair

**Review by DieselMohawk — APPROVED** [review]
Good job me and Rot, thanks us for our contribution?

**Comment by FluffMe** [comment]
> Good job me and Rot, thanks us for our contribution?

Rot, unfortunately, removed from credits :( as kos is removed :(

**Comment by DieselMohawk** [comment]
> > Good job me and Rot, thanks us for our contribution?
> 
> Rot, unfortunately, removed from credits :( as kos is removed :(

Damn

**Comment by KeldWolf** [comment]
Are we feeling like this is ready to rock soon?

**Review by KeldWolf — APPROVED** [review]

**Comment by FluffMe** [comment]
As a sole author I am double licensing the code.
It's now available under MIT.

PR description updated to reflect this

**Pull request merged**
