### PR TITLE
Return of the Sheriff Hat

### PR DESCRIPTION
**Pull request by BoskiYourk**
## About the PR
- Added a new and refreshed version of the old HoS hat back to the game.

## Why / Balance
Others and my self Yearned for it to come back.

### _Harmony Namescape

Resources/Textures/_Harmony/Clothing/Head/Hats/hoswidebrimhat.rsi -- Hat texture location
Resources/Prototypes/_Harmony/Entities/Clothing/Head/hats.yml -- Hat entity location
Resources/Prototypes/_Harmony/Recipes/Lathes/clothing.yml -- Hat lathe recipe location
Resources/Prototypes/_Harmony/Loadouts/Jobs/Command/head_of_security.yml -- Hat loadout location

### Upstream Files

Resources/Prototypes/Entities/Structures/Machines/lathe.yml -- Adds the hat as an option to make in the uniform printer
Resources/Prototypes/Loadouts/loadout_groups.yml -- Adds the hat to its proper loadout group

## Media

HoS hat PR
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added the HoS sheriff hat back to the game.

### CODE REVIEW

**Comment by FluffMe** [comment]
Yeeeehaaaaw!

**Comment by DieselMohawk** [comment]
Good work.

**Comment by BoskiYourk** [comment]
Alright, all mentions of Stetson have been removed. If I need to provide new loadout and late screenshots I can.

**Comment by FluffMe** [comment]
> Alright, all mentions of Stetson have been removed. If I need to provide new loadout and late screenshots I can.

Please do

**Comment by BoskiYourk** [comment]
> > Alright, all mentions of Stetson have been removed. If I need to provide new loadout and late screenshots I can.
> 
> Please do

Here you go!

image
image

**Review by FluffMe — DISMISSED** [review]
Code looks good.

Good job!

**Comment by FluffMe** [comment]
> "copyright": "Taken and Updated from cev-eris at commit [discordia-space/CEV-Eris@a75dee2](https://github.com/discordia-space/CEV-Eris/commit/a75dee2e6d236612dbd403dd5f8687ca930c01f1) by BoskiYourk for use in Harmony"
> 
> Change the given commit to "[discordia-space/CEV-Eris#1073](https://github.com/discordia-space/CEV-Eris/pull/1073)" since this is where the hat is actually taken from.

commit for this PR is `https://github.com/discordia-space/CEV-Eris/commit/3a941632978abfa69290c961ffb55db5e665aa69`

**Comment by DieselMohawk** [comment]
> > "copyright": "Taken and Updated from cev-eris at commit [discordia-space/CEV-Eris@a75dee2](https://github.com/discordia-space/CEV-Eris/commit/a75dee2e6d236612dbd403dd5f8687ca930c01f1) by BoskiYourk for use in Harmony"
> > Change the given commit to "[discordia-space/CEV-Eris#1073](https://github.com/discordia-space/CEV-Eris/pull/1073)" since this is where the hat is actually taken from.
> 
> commit for this PR is `https://github.com/discordia-space/CEV-Eris/commit/3a941632978abfa69290c961ffb55db5e665aa69` Thanks for finding it. We did some digging in discord DMs and gave up.

Call me the digger.

**Review by DieselMohawk — APPROVED** [review]

**Review by FluffMe — APPROVED** [review]

**Comment by BoskiYourk** [comment]
What a process. Glad it's done, though!

**Comment by DieselMohawk** [comment]
> What a process. Glad it's done, though!

It's a learning process, thanks for your contribution.

**Comment by FluffMe** [comment]
> What a process. Glad it's done, though!

Thanks for bearing with us!

**Comment by DieselMohawk** [comment]
Build failure, gonna test it

**Comment by FluffMe** [comment]
> Build failure, gonna test it

It's upstream test bug. I am rerunning

**Pull request merged**
