### PR TITLE
Detective Spriting Update: Searching for Good Drip

### PR DESCRIPTION
**Pull request by BoskiYourk**
## About the PR

- Updated both of the detective's trenchcoat sprites
- Updated both of the fedora sprites

## Why / Balance

People have wanted the old sprites updated since they were forcefully merged against community wishes. The original spriter won't let the old sprites be updated, so I've decided to PR it as a Harmony exclusive.
### _Harmony Namescape
Resources/Textures/_Harmony/Clothing/Head/Hats/brownfedora.rsi -- Brown fedora texture location
Resources/Textures/_Harmony/Clothing/Head/Hats/greyfedora.rsi -- Grey fedora texture location
Resources/Textures/_Harmony/Clothing/OuterClothing/Coats/detective.rsi -- Det coat texture location
Resources/Textures/_Harmony/Clothing/OuterClothing/Coats/detective_grey.rsi -- Grey det coat texture location

### Upstream Files
Resources/Prototypes/Entities/Clothing/Head/hats.yml -- Updated fedora sprite pathing
Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml -- Updating det coat sprite pathing

## Media

Harmony PR Detective 1
Harmony PR Detective 2

Harmony PR Detective 3
Harmony PR Detective 4

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Updated the detective's trenchcoats and fedoras

### CODE REVIEW

**Review by DieselMohawk — APPROVED** [review]
Looking good.

**Comment by FluffMe** [comment]
> The original spriter won't let the old sprites be updated, so I've decided to PR it as a Harmony exclusive.

Can you elaborate?

**Comment by DieselMohawk** [comment]
> > The original spriter won't let the old sprites be updated, so I've decided to PR it as a Harmony exclusive.
> 
> Can you elaborate?

I can explain it in DMs if you'd like.

**Review by FluffMe — APPROVED** [review]
Shuffled comments around a bit.

Approved!

**Review by DieselMohawk — APPROVED** [review]

**Pull request merged**
