### PR TITLE
Cargo QoL: Add dropdown with list of crew members to order menu

### PR DESCRIPTION
**Pull request by FluffMe**
## About the PR
Adds a crew list `OptionButton` to the Cargo console Order menu.

## Why / Balance
This allows to quickly fill out the `Name` field of the order. See the attached video.
If the requester name is too long or too complicated, or they left and you forgot their name while common going crazy -- it's easy to forget or type in the wrong name.
Usually, cargo techs default to their name in this field in these cases (at least I do) or even in all cases.

This QoL feature should make selecting the requesters much easier and will make the blue order slips mostly perfect for the paperwork nerds.
It might also provide an opportunity for spotting the people that are not on the manifest, if this is important for the round.

Vanilla functionality is unchanged. You can still type in anything in this field, if you want to.

## Technical details
- `Content.Shared/Cargo/BUI/CargoConsoleInterfaceState.cs`
    * `crewManifest` added to the state and its constructor
- `Content.Server/Cargo/Systems/CargoSystem.Orders.cs`
   * `UpdateOrderState()` is the updater of the `CargoConsoleInterfaceState`. Now fetches the crew manifest with `CrewManifestSystem.GetCrewManifest()` and constructs the state with it.
- `Content.Client/Cargo/BUI/CargoOrderConsoleBoundUserInterface.cs`
    * Console BUI. Now calls for `PopulateCrewList()` method of `CargoConsoleOrderMenu.xaml.cs` and passes the crew manifest entries to it.
- `Content.Client/Cargo/UI/CargoConsoleOrderMenu.xaml`
    * XAML for the Order menu. Added the `OptionButton`.
- `Content.Client/Cargo/UI/CargoConsoleOrderMenu.xaml.cs`
    * Controller for the Order menu. Now has `PopulateCrewList()` method to populate the list and `OnCrewMemberSelected()` handler for when the item in the list is selected.
- `Resources/Locale/en-US/_Harmony/cargo/cargo-console-order-component.ftl`
    * Loc strings.

## Media
https://github.com/user-attachments/assets/65983367-3555-49e8-b9a3-e3c1227978de

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- add: Added a crew manifest dropdown to the Cargo console Order menu. Paperwork mains sould have an easier time having their shipments in order.

### CODE REVIEW

**Comment by FluffMe** [comment]
@KeldWolf as this modifies a lot of upstream code, I am not sure if it's better suited as an upstream PR, rather than a Harmony PR. Your call.

@SlamBamActionMan I would appreciate your opinion as an upstream maintainer on whether this is needed upstream.

**Comment by SlamBamActionman** [comment]
> @KeldWolf as this modifies a lot of upstream code, I am not sure if it's better suited as an upstream PR, rather than a Harmony PR. Your call.
> 
> @SlamBamActionman I would appreciate your opinion as an upstream maintainer on whether this is needed upstream.

I could see this being used upstream; it's a neat feature, probably not necessary (though I am notoriously bad at doing cargo paperwork) but it has its uses!

My main concern is how it selects the name list, but it looks like it uses the crew manifest so that should probably work. Probably would be nice if it was sorted alphabetically but maybe that's not super important.

**Comment by FluffMe** [comment]
I feel like it should be affected. Why cargo computer should be better than any other one. Everyone gets the error!

That's if the crew manifest is affected by clerical errors. I think it is?

**Review by KeldWolf — APPROVED** [review]
This sorta thing rules. Can't wait to see it.

**Pull request merged**
