### PR TITLE
 Add 4 more posters by LevitatingTree

### PR DESCRIPTION
**Pull request by FluffMe**
## About the PR
Add "Fallen Can", "Faded Poster", "Magic Candle", and "Super-Matter" posters by LevitatingTree

## Why / Balance
MOAR!!!

## Technical details
id 7 skipped for https://github.com/ss14-harmony/space-station-14/pull/64

## Media
image

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None

**Changelog**
- add: Added "Fallen Can", "Faded Poster", "Magic Candle", and "Super-Matter" posters by LevitatingTree.

### CODE REVIEW

**Review by KeldWolf — COMMENTED** [review]
Cool S made me chuckle. I'm of an age where I drew many in the margins of a notebook But, it's kinda just unrelated random memey and is a little low effort. I'll let someone else chime in on it or approve it.

**Comment by FluffMe** [comment]
Cool S is also almost invisible in poor lighting situations

**Comment by FluffMe** [comment]
Removed "Cool S" after discussion with the author.

**Comment by FluffMe** [comment]
After changes:

image

**Review by KeldWolf — APPROVED** [review]
These looks great. Approved and adding.

**Pull request merged**
