### PR TITLE
Add New Lobby Track "Rusty Cans (Battle)"

### PR DESCRIPTION
**Pull request by spanky-spanky**
## About the PR
Adds new lobby track "Rusty Cans (Battle)," originally composed for FTL Captain's Edition by Aaron Opfer under CC BY-NC-SA 3.0.

## Why / Balance
There's interest in custom Harmony lobby music so I am making this to (hopefully) serve as a template for future tracks. This is one of my favorite tracks from FTL Captain's edition and I was able to find the file and attributions in the code for it, and have brought it here. [Link to the modpack](https://subsetgames.com/forum/viewtopic.php?t=15663)

## Technical details
- `Resources/Audio/_Harmony/Lobby/rustycansbattle.ogg` -- New /Lobby folder and audio track inside.
- `Resources/Audio/_Harmony/Lobby/attributions.yml` -- Attributions for Harmony lobby tracks.
- `Resources/Prototypes/SoundCollections/lobby.yml` -- Adds rustycansbattle.ogg to lobby music track listing.

## Media
[Youtube link](https://www.youtube.com/watch?v=rJ0WK-t6GtU)
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: New lobby track, "Rusty Cans (Battle)."

### CODE REVIEW

**Review by KeldWolf — APPROVED** [review]
I appreciate this templating for the future as well.

**Comment by spanky-spanky** [comment]
Waiting for confirmation from FluffMe that the structuring is right.

**Review by FluffMe — APPROVED** [review]
Looks legit!

**Comment by FluffMe** [comment]
Added a screeny in lobby to the PR media section

**Pull request merged**
