### PR TITLE
Add Drobe-available items to Loadouts -- red bandana for SecOff, brown bandana for CargoTech, noir coat for Det

### PR DESCRIPTION
**Pull request by FluffMe**
## About the PR
- Remove misspelled and unused folder `Loadlouts` from `Harmony` namespace.
- Add "brown bandana" to Cargo Tech loadout.
- Add "red bandana" to Security Officer loadout.
- Add "noir trenchcoat" to Detective loadout.

## Why / Balance
All three items are readily available at respective departments' Drobes.
Requested by players to streamline their preferred character look round start.

### `Harmony` namespace
- `Resources/Prototypes/Harmony/Loadlouts/*` removed. Misspelled, and contains only commented out files. @KelfWolf, please check.
- `Resources/Prototypes/Harmony/Loadouts/Jobs/Cargo/cargo_technician.yml` -- new loadout options.
- `Resources/Prototypes/Harmony/Loadouts/Jobs/Security/detective.yml` -- new loadout options.
- `Resources/Prototypes/Harmony/Loadouts/Jobs/Security/security_officer.yml` -- new loadout options.
### Upstream modifications
- `Resources/Prototypes/Loadouts/loadout_groups.yml` -- introduces the options above to loadout groups. Properly commented.

## Media
image
image
image

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: Add "brown bandana" as a headwear option for Cargo Tech loadout.
- add: Add "red bandana" as a headwear option for Security Officer loadout.
- add: Add "noir trenchcoat" as a outer clothing option for Detective loadout.

### CODE REVIEW

**Comment by FluffMe** [comment]
@KeldWold this modifies your previous work on pins, so please take a closer look at what I am deleting.

**Comment by FluffMe** [comment]
Waiting for https://github.com/space-wizards/space-station-14/pull/32380 resolution before merging.

**Review by KeldWolf — APPROVED** [review]
Yep, good to see that stuff getting cleaned up. The changes are good. I like the "drobes" being a place to get other stuff during the round. But, loadouts are really where folks express themselves and I'm all for more options there.

**Review by KeldWolf — APPROVED** [review]
Forgot to approve =D

**Pull request merged**
