### PR TITLE
Legal cat ears and feline headwear crate

### PR DESCRIPTION
**Pull request by FluffMe**
## About the PR
- Added a version of cat ears, "corporate-approved cat ears", that is not considered Syndicate contraband, and lacks Valid tagging.
- Added "feline headwear crate" to cargo requests that contains 3 corporate-approved cat ears. Costs 3000 spesos, which makes it 1000 per pair of cat ears.

## Why
To make cat ears from luck based unobtanium and/or syndicate-only item into a legal and affordable Cargo purchase.
Now sec can OwO and not be in breach of their own rules.

## Technical details
- Added new cat ears entity.
- Added crate entity.
- Added crate to cargo requests.

All in Harmony namespace.

## Media
image

**Changelog**
:cl:
- add: corporate-approved cat ears added to the game. Ordered from cargo (3000 spesos for a crate of 3)

### CODE REVIEW

**Comment by FluffMe** [comment]
Price is subject to changes XD

**Comment by Nonagon44** [comment]
I'm seeing an issue with this as sec knows regular cat ears are contra and now they will have to individualy check people's cat ears for a contraband tag.
Imo would be best to keep em as is but. Keld might have a different opinion so take my opinion with a grain of salt.

**Comment by FluffMe** [comment]
> I'm seeing an issue with this as sec knows regular cat ears are contra and now they will have to individualy check people's cat ears for a contraband tag. Imo would be best to keep em as is but. Keld might have a different opinion so take my opinion with a grain of salt.

Resprite of legal version to make them different color may be in order then. Or it's an additional difficulty to check legality of an item for sec.

IMO, they had to figure out if it's salvage/gambling obtained anyway and make decision on confiscation.
If anything, that reduces the check time for sec officer.

**Comment by Nonagon44** [comment]
Yeah a sprite change would would! Alter one of the ears slightly just so sec doesn't valid hunt cat ears lol

**Comment by FluffMe** [comment]
Bump! Are we

- Respriting legal version.
- Keep PR as is.
- Not merging at all?

Opinions welcome! And rebased to pass checks.

**Comment by KeldWolf** [comment]
There's some question about whether this is just sorta low effort felinid if we add them in. It's generally the same people who want them each round instead of an occasional rare and even hushed tones illegal item. If we add them in like this it removes them from being a contraband thing. I currently like it being that way or the occasional admin grant. That said I'd like to hear what others have to say.

**Comment by spanky-spanky** [comment]
After some admin discussion we've decided we'd like to keep cat ears as contraband and non-cargo purchasable. If in future we want to provide this or something similar we can reapproach/reopen this.

**Pull request closed without merging**
