### PR TITLE
Cocktail set #1

### PR DESCRIPTION
**Pull request by Unisol**
## About the PR
Added three new cocktails along with custom recipes and graphics: aviation, espresso martini, sunset soda.

## Technical details
Everything is in `Harmony` folders, except for spawner changes:
- `Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/drinks_glass.yml` -- added to spawner with `# Harmony` comment

## Media
SS14 Loader_OvYrR6hn5M
SS14 Loader_eExjiPbOWX

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Added Aviation number 3, espresso martini and sunset soda to list of cocktails

### CODE REVIEW

**Comment by FluffMe** [comment]
I'll give it a thorough look in the next couple of days!

**Comment by Unisol** [comment]
I've moved all changes to harmony-specific subfolders; this should be good to review.

**Review by FluffMe — APPROVED** [review]
* Removed locale files. Harmony is an English-only server, and maintaining locales is currently not needed. If someone will get on localization efforts for Harmony-only content, we will reintroduce it.
* Moved the strings from locale .ftl files into reagents' `name` and `desc` themselves.
* Changed name capitalization to be in line with the rest of the game.

Otherwise, LGTM. Sorry for the direct edits! Please wait for @KeldWolf to merge.

You have to make aviation for me now!

**Comment by FluffMe** [comment]
Ah, I see. Linter expects the localization messages XD
This makes more sense now! I'll revert.

**Review by FluffMe — DISMISSED** [review]
Attempt number two! +

**Review by KeldWolf — APPROVED** [review]
Perfect. Thanks for making our life easier in the future.

**Pull request merged**
