### PR TITLE
new hud theme

### PR DESCRIPTION
**Pull request by jack-thedragon95**
## About the PR
Added new hud ~~"GAH I LOVE BEING PURPLE"~~ "Purplicious"

## Why / Balance
mqdefault

## Technical details
purple

## Media
image
[i added the name after this screeen cap was taken :)]

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
purple

### CODE REVIEW

**Comment by ps3moira** [comment]
While this is cool, you didn't localize anything. Should make the proper changes in the folders marked for harmony

**Comment by FluffMe** [comment]
@jack-thedragon95 merged origin/master into your branch. Should look neat and pass checks now.

**Comment by FluffMe** [comment]
PS: I'll move namespaces to Harmony to keep it separate from upstream as much as possible on the weekend.

**Review by FluffMe — COMMENTED** [review]
- Namespaced everything to `Harmony`
- `Resources/Locale/en-US/escape-menu/ui/options-menu.ftl` is the only upstream namespace modified, ~~commented properly~~.
- Changed IDs and Paths to `HarmonyPurple` (not all, but important ones).

LGTM otherwise.

**Comment by jack-thedragon95** [comment]
thanks!... now we continue to wait :)

**Review by KeldWolf — CHANGES_REQUESTED** [review]
That ID/name is a little rough. Could we at least get the name to one word so it's in line with the other themes? I enjoy the reference. But, it's a lot =)

**Comment by jack-thedragon95** [comment]
alright ill think of something up to replace it

**Comment by FluffMe** [comment]
Purplicious

**Comment by jack-thedragon95** [comment]
that could work! THANKS!!!

**Review by KeldWolf — APPROVED** [review]
Looks good. Approved and merging

**Pull request merged**
