### PR TITLE
Mind if we call it “Bruce” to keep it clear?

### PR DESCRIPTION
**Pull request by Unisol**
## About the PR
Added a lawset board for Walamalawset, with laws loosely based on rules of the philosophy department at the University of Walamaloo.

## Why / Balance
Boredom

## Technical details
Board is not mapped or obtainable in any way other than admin intervention.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Review by FluffMe — COMMENTED** [review]
Code is good!

**Comment by FluffMe** [comment]
Screenshot for the review
image

**Comment by spanky-spanky** [comment]
An alternative to this is to add the lawset into the pool for borg ion storm laws, rather than making it an option for the Station AI. The AI is already a pain for syndicates and making it both silly and able to more or less validhunt sounds like less fun for everyone.

**Comment by Unisol** [comment]
I don't really remember why I made this, I think I was drunk one day and thought it would be funny.

**Comment by FluffMe** [comment]
It is funny. But we should remake it into ion storm borg lawset, ye

**Comment by FluffMe** [comment]
@Unisol I'll close this for now. Feel free to open another PR for ion storm laws.

**Pull request closed without merging**
