### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by FluffMe**
## About the PR
Fixing various issues with IntegrationTests

## Why / Balance
I have nightmares about the red cross.

## Technical details
- **Important one** -- Spanky's map is added to **PostMapInitTest.cs**. `AllMapsTested` assertion fails without it.
- Various shuttles butchered via yaml editing to kill "No space!" and the UID '0' issues.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
@spanky-spanky needs to load and test affected shuttles.

### CODE REVIEW

**Comment by FluffMe** [comment]
Please be green...

**Comment by FluffMe** [comment]
IT'S GREEN!!!

**Review by KeldWolf — APPROVED** [review]
We're looking good. Tests are passing and proper org permissions are set. Merging this.

**Comment by Nonagon44** [comment]
ITS A HARMONY  MIRACLE! All green! LETS GOOOO

**Pull request merged**
