### PR TITLE
Harmony Instructor Mantle

### PR DESCRIPTION
**Pull request by Tsawodi**
**Disclaimer:** Sorry if this is the wrong process for this, I wasn't sure where to ask about it in the Discord.

### Description:
Added the instructor mantle. Can only spawned in through the entity menu.

### File Changes:
\+ Resources\Textures\Harmony\Clothing\Neck\Misc\instructormantle.rsi 
∟\+ .\equipped-NECK.png
∟\+ .\icon.png
∟\+ .\meta.json
\+ Resources\Prototypes\Harmony\Entities\Clothing\Neck\mantles.yml

### Reasoning:
There is no real reason other than that it would be fun for the teach and learn day(s).

### Media:
instructor_mantle
instructor_mantle_desc
instructor_mantle_greytide

### CODE REVIEW

**Review by KeldWolf — DISMISSED** [review]
This looks great. Perfect for tomorrow!

**Comment by KeldWolf** [comment]
This seems to be failing the YAML linter. Can you see if there's something up with the meta or prototype's yaml that might be causing it? I can take a look a little later too.

**Comment by FluffMe** [comment]
@KeldWolf @Tsawodi from a quick glance the issue seems to be with slashes used in sprite paths.

`\` should be replaced with `/`

**Comment by Tsawodi** [comment]
Woops, didn't mean to dismiss the review, I don't really know how to use Github properly yet.

@FluffMe Pretty sure that's exactly what it was since I copy-pasted the directories from Windows Explorer. Certified Windows moment.

**Comment by FluffMe** [comment]
> Woops, didn't mean to dismiss the review, I don't really know how to use Github properly yet.
> 
> @FluffMe Pretty sure that's exactly what it was since I copy-pasted the directories from Windows Explorer. Certified Windows moment.

No worries. I'll add a review, since keld approved it already.
Build still faced due to one missed slash:
https://github.com/ss14-harmony/space-station-14/blob/826be254f60d7e1eb8754984691830ddd3f5a755/Resources/Prototypes/Harmony/Entities/Clothing/Neck/mantles.yml#L8

**Comment by Tsawodi** [comment]
I should've just find and replaced it but I'm dumb

**Review by FluffMe — APPROVED** [review]
Good to merge. Was approved by Keld before.

**Pull request merged**
