### PR TITLE
Barratry Update (Holopads & Engi)

### PR DESCRIPTION
**Pull request by spanky-spanky**
## About the PR
Adds holopads, atmospheric network monitor and sensors, and advanced SMES's to Barratry.
**Requires upstream merge.**

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by spanky-spanky** [comment]
This requires a plethora of new upstream content and will fail at the moment.

**Comment by KeldWolf** [comment]
It's still failing the build/test action so I'm not going to try and push this in last minute. Which sucks. But, we'll have it in for next time.

**Comment by spanky-spanky** [comment]
I probably missed an invalid, won’t be able to fix for a bit anyways.

**Review by FluffMe — APPROVED** [review]
* Merged master
* Fixed invalid

**Pull request merged**
