### PR TITLE
Upstream20241201

### PR DESCRIPTION
**Pull request by KeldWolf**
Routine Upstream merge for Dec. 1, 2024

### CODE REVIEW

**Comment by BoskiYourk** [comment]
WOW!!! THIS IS REALLY GOOD STUFF!!

**Comment by TheCrimsonJupiter** [comment]
Let's rock and roll!

**Review by spanky-spanky — APPROVED** [review]

**Comment by Unisol** [comment]
Could you please add comment on line 218 of ``Content.Server\Anomaly\Components\MaintainerGullibilityComponent.cs`` about what was changed?

**Comment by KeldWolf** [comment]
Routine upstream merge

**Pull request merged**
