### PR TITLE
New Syndicate Reinforcement Shuttle + Remove Instigator

### PR DESCRIPTION
**Pull request by spanky-spanky**
## About the PR
- Adds new Syndicate Reinforcement shuttle and gamerule.
- Removes Instigator ship from the unknown shuttle pool.

## Why / Balance
Part 2 of a series of new mid-round shuttles. This one aims to provide a more balanced and RP capable antagonist shuttle to replace the now removed Instigator shuttle, which has had admin consensus of being unsuited for Harmony.

The pictured shuttle spawns with a syndicate spy reinforcement and monkey agent, both of which will spawn with their own objectives. On the table is a syndicate PDA (for access), an uplink with 10TC (enough to be creative but not overpowered), and also a suspicious toolbox. Not pictured is a stack of plasma to power the P.A.C.M.A.N. generator which keeps the ship from running indefinitely, since shuttle antags can get carried away.

## Media
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: New visiting shuttle event "Syndicate Reinforcement."
- remove: Removed Instigator from shuttle event pool.

### CODE REVIEW

**Review by FluffMe — APPROVED** [review]

**Comment by TheCrimsonJupiter** [comment]
A fair trade.

**Comment by spanky-spanky** [comment]
Speed approval, but waiting for admin input before self merging.

**Comment by KravinDes** [comment]
Which type of suit is in that EVA container? Also, I feel that the monkey might add simply too much value. Without the monkey, they're sitting on about 12 TC worth of free items (Assuming its a normal EVA), 8 of which comes from the syndicate spy kit. Being able to use something like the syndicate disaster victim would be nice, since they can spawn as any race. However, the issue with that suggestion is the fact they aren't a full antagonist unless they roll sleeper. They are however still a free agent, but the lack of direction could also cause issues.  On another note, getting rid of the instigator is pretty well warranted. It was just murderbone express since it didn't start the nukie game rule. I'm going to miss it's design though.

**Comment by spanky-spanky** [comment]
> Which type of suit is in that EVA container? Also, I feel that the monkey might add simply too much value. Without the monkey, they're sitting on about 12 TC worth of free items (Assuming its a normal EVA), 8 of which comes from the syndicate spy kit. Being able to use something like the syndicate disaster victim would be nice, since they can spawn as any race. However, the issue with that suggestion is the fact they aren't a full antagonist unless they roll sleeper. They are however still a free agent, but the lack of direction could also cause issues. On another note, getting rid of the instigator is pretty well warranted. It was just murderbone express since it didn't start the nukie game rule. I'm going to miss it's design though.

The suit is a basic syndicate EVA. I've tested this on a few rounds and it has added to the atmosphere and not felt overpowered. The aim isn't to balance it as a crewmember but rather as an otherwise disadvantaged infiltrator, without any crew access (including maints), and a suspicious name.

**Comment by YoungThugSS14** [comment]
Oh yeah I got to use this on a previous shift! I really like it as it encourages antag creativity with the amount of TC you get aswell

**Pull request merged**
