### PR TITLE
Add Hypophonia (soft speech, whisper only) trait

### PR DESCRIPTION
**Pull request by FluffMe**
## About the PR
Adds a [Hypophonia](https://en.wikipedia.org/wiki/Hypophonia) trait to the Disabilities section. The trait forces you to whisper and doesn't allow to scream.
Death gasp, fake death gasp, etc. are unaffected

## Why / Balance
More role play and character customization => More better

## Technical details
`SpeakAttemptEvent` lacked data on what exactly is spoken. The following changes were made to rectify this:
- `Content.Shared/Speech/SpeakAttemptEvent.cs` -- `SpeakAttemptEvent` now has a `Whisper` bool.
- `Content.Shared/ActionBlocker/ActionBlockerSystem.cs` -- `CanSpeak()` is the only function that raises this event. Incorporates `whisper` boolean flag in args and raise and defaults it to `false`.
- `Content.Server/Chat/Systems/ChatSystem.cs` -- `SendEntityWhisper()` calls `CanSpeak()` with `whisper` set to `true`
Now any whisper `SpeakAttemptEvent` has a `Whisper` member set to `true`

`_Harmony`
- `Content.Shared/_Harmony/Hypophonia/HypophoniaComponent.cs` -- component
- `Content.Server/_Harmony/Speech/Hypophonia/HypophoniaSystem.cs` -- system
    * `HypophoniaSystem` is largely based on `MutingSystem`.
    * It could conflict with mime/muted stuff, so I made sure it nopes out and lets `MutingSystem` handle things, when `Muted` component is present.

- `Resources/Prototypes/_Harmony/Traits/disabilities.yml` -- trait proto
- `Resources/Locale/en-US/_Harmony/traits/traits.ftl` -- trait loc strings
- `Resources/Locale/en-US/_Harmony/speech/speech-effects.ftl` -- speech popup loc strings

## Media
image

https://github.com/user-attachments/assets/66c3e1a4-f573-44c8-be33-f867cc0ddea4

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None

**Changelog**
:cl:
- add: Added Hypophonia trait. With this trait you have a very soft voice and can only whisper.

### CODE REVIEW

**Comment by FluffMe** [comment]
Will merge conflict with #149 due to modifications of traits.ftl

**Comment by cfif126** [comment]
Shouldn't just block from speaking loudly using local chat, the transformation of message to whisper would be more intuitive and smoother

**Comment by FluffMe** [comment]
> Shouldn't just block from speaking loudly using local chat, the transformation of message to whisper would be more intuitive and smoother 

This would require some changes in `ChatSystem.cs` and, possibly, how `CanSpeak()` works. Or rather a new method.

I'll look into it, but it doesn't sound very easy from the get go.

Feel free to push, if you have a quick idea on implementation.

**Review by KeldWolf — DISMISSED** [review]

**Review by KeldWolf — APPROVED** [review]
Approved due to bully /s

**Pull request merged**
