### PR TITLE
Update to RSC rifle and RSC rifle crate

### PR DESCRIPTION
**Pull request by Unisol**
## About the PR
Changed texture on bolt-action rifle crate to old wooden texture provided by thesaladmancer. Changed RSC rifle to be stripper-clip fed as opposed to internal magazine fed.

## Why / Balance
To further distance RSC from Mosin, RSC now uses stripper clips as magazines and autoejects them when empty (audio for inserting and ejecting clips courtesy Nonagon).

## Media
See [thread ](https://discord.com/channels/1139716325627932682/1295542535426412564) for video presentation of rifle mechanics.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: bolt-action rifle crate received a facelift
- RSC now feeds off stripper clips and ejects empty clips with a very specific *PING*

### CODE REVIEW

**Review by FluffMe — APPROVED** [review]
@Unisol I've debugged the audio system in `RobustToolbox/Robust.Client/Audio/AudioSystem.cs` by placing a breakpoint on the line 451 that is in charge of playing an entity if all conditions are correct.

```csharp
            return PlayEntity(sound, Filter.Local(), source, false, audioParams);
```

It, as expected, played 3 sounds at the same time: `garand-ping-short.wav`, `garand-ping-rattle.wav`, and a `sniper.ogg` shot sound.

Unless the issue is with misprediction, it's probably a sound overlay issue.
You can attempt adding a quiet time to ping-rattle that is slightly more than ping-short to see if it helps and see if I diagnosed it right.
Feel free to place a breakpoint yourself to monitor what plays and when.

I don't see it as a blocker, so approved.

**Comment by Unisol** [comment]
> You can attempt adding a quiet time to ping-rattle that is slightly more than ping-short to see if it helps

This is how it's been since the very beginning, I had split the ping file into ping and rattle and kept the quiet section in the front of the rattle with the same duration as ping. When I added extra silence at the end of the ping file, double ping became more pronounced, suggesting that it in fact plays twice.

**Review by DieselMohawk — APPROVED** [review]

**Comment by FluffMe** [comment]
> > You can attempt adding a quiet time to ping-rattle that is slightly more than ping-short to see if it helps
> 
> This is how it's been since the very beginning, I had split the ping file into ping and rattle and kept the quiet section in the front of the rattle with the same duration as ping. When I added extra silence at the end of the ping file, double ping became more pronounced, suggesting that it in fact plays twice.
> 
> @FluffMe btw, is that issue replicated on your setup at all?

Yeah, Funnily enough i can hear it better if I don't debug it.

https://github.com/user-attachments/assets/ab66adf6-73fa-4073-ba53-a71238a0caf7

Sounds are replaced with 2 different debug tones. Rattle one with silence.
First go is not logged, second one logpoint is added.

While playing is called only once, i can still hear artifacts/repetition.

**Comment by FluffMe** [comment]
Maybe it's just about playing too much stuff at the same time. No idea!

**Comment by Unisol** [comment]
It sounds like an upstream bug, if anything. The only other entity that uses the autoeject feature is the C-20r, and it has very quiet mag eject sound accompanied by a very loud beeping for mag empty sound. It's reasonable to assume it's gone unnoticed so far. In any case, I think it's out of scope for this PR to fix.

**Pull request merged**
